export const userInputs = [
    {
        id:1,
        label:'Username',
        type:'text',
        placeholder:'tolasa_ganati',
    },
    {
        id:2,
        label:'Name and surname',
        type:'text',
        placeholder:'Anile Hinsesu',
    },
    {
        id:3,
        label:'Email',
        type:'mail',
        placeholder:'Anile@gmail.com',
    },
    {
        id:4,
        label:'Phone',
        type:'text',
        placeholder:'+2519838383',
    },
    {
        id:5,
        label:'Password',
        type:'password',
    },
    {
        id:6,
        label:'Adress',
        type:'text',
        placeholder:'Adama',
    },
    {
        id:7,
        label:'country',
        type:'text',
        placeholder:'Ethiopia',
    }
]